services:
  server:
    image: ghcr.io/talebook/book-review-server:latest
    restart: always
    volumes:
      - ./data/sqlite:/data
      - ./brs.log:/app/brs.log
    ports:
      - "5002:80"
    env_file:
      - .env
